#!/bin/bash
set -eu

VERSION=${VERSION:-1.18.8}

# check https://github.com/kubernetes/kubernetes/releases
rm -rf tmp; mkdir tmp
for x in kube-{apiserver,controller-manager,proxy,scheduler} kubectl kubelet; do
  echo ">> updating k8s core component '$x'..."
  curl -Lo tmp/$x  "https://storage.googleapis.com/kubernetes-release/release/v${VERSION}/bin/linux/amd64/${x}"
  if ! file tmp/$x | grep -iq 'elf 64-bit lsb executable'; then
    echo >&2 "failed to download k8s core component '$x':"
    file tmp/$x
    exit 1
  else
    bosh add-blob tmp/$x k8s/$x
  fi
done

echo ">> rebuilding dockerized k8s components..."
make dockers VERSION=$VERSION

# check https://github.com/containerd/containerd/releases
v=1.3.7
echo ">> updating containerd to $v..."
what=containerd-${v}-linux-amd64.tar.gz
curl -Lo tmp/${what} https://github.com/containerd/containerd/releases/download/v${v}/${what}
tar -tzf tmp/${what}
bosh add-blob tmp/${what} containerd/${what}

# check https://github.com/containernetworking/plugins/releases
v=0.8.6
echo ">> updating cni-plugins to $v..."
what=cni-plugins-linux-amd64-v${v}.tgz
curl -Lo tmp/${what} https://github.com/containernetworking/plugins/releases/download/v${v}/${what}
tar -tzf tmp/${what}
bosh add-blob tmp/${what} containerd/${what}

# check https://github.com/kubernetes-sigs/cri-tools/releases
v=1.18.0
echo ">> updating crictl to $v..."
what=crictl-v${v}-linux-amd64.tar.gz
curl -Lo tmp/${what} https://github.com/kubernetes-sigs/cri-tools/releases/download/v${v}/${what}
tar -tzf tmp/${what}
bosh add-blob tmp/${what} containerd/${what}

# check https://github.com/opencontainers/runc/releases
v=1.0.0-rc10
what=runc
echo ">> updating runc to $v..."
curl -Lo tmp/${what} https://github.com/opencontainers/runc/releases/download/v${v}/runc.amd64
bosh add-blob tmp/${what} runtime-runc/${what}

v=latest
what=runsc
echo ">> updating runsc to $v..."
curl -Lo tmp/${what} https://storage.googleapis.com/kubernetes-the-hard-way/runsc-50c283b9f56bb7200938d9e207355f05f79f0d17
bosh add-blob tmp/${what} runtime-runc/${what}

# check https://github.com/etcd-io/etcd/releases
v=3.4.10
echo ">> updating etcd to $v..."
what=etcd-v${v}-linux-amd64.tar.gz
curl -Lo tmp/${what} https://github.com/etcd-io/etcd/releases/download/v${v}/${what}
tar -tzf tmp/${what}
bosh add-blob tmp/${what} etcd/${what}

v=latest
echo ">> updating cfssl to $v..."
what=cfssl_linux-amd64
curl -Lo tmp/${what} https://pkg.cfssl.org/R1.2/${what}
bosh add-blob tmp/${what} cfssl/${what}

v=latest
echo ">> updating cfssljson to $v..."
what=cfssljson_linux-amd64
curl -Lo tmp/${what} https://pkg.cfssl.org/R1.2/${what}
bosh add-blob tmp/${what} cfssl/${what}
